import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { authenticateMerchant } from "@/lib/api/merchant-auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { initializeCheckout, selectProvider } from "@/lib/providers";
const schema=z.object({decision:z.enum(["approve","reject"])});
export async function POST(req:NextRequest,{params}:{params:Promise<{id:string}>}){
 const {id}=await params;const auth=await authenticateMerchant(req);if(!auth.ok)return NextResponse.json({error:auth.error},{status:auth.status});if(auth.kind==="api_key")return NextResponse.json({error:"Manual review requires a signed-in user"},{status:403});
 const parsed=schema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid decision"},{status:400});
 const {data:visible}=await auth.supabase.from("payment_transactions").select("*").eq("id",id).maybeSingle();if(!visible)return NextResponse.json({error:"Not found"},{status:404});const {data:membership}=await auth.supabase.from("merchant_members").select("role").eq("merchant_id",visible.merchant_id).eq("user_id",auth.user.id).maybeSingle();if(!membership||!["owner","admin","analyst"].includes(membership.role))return NextResponse.json({error:"Forbidden"},{status:403});
 let admin;try{admin=createAdminClient()}catch{return NextResponse.json({error:"Server payment operations are not configured"},{status:503})}const {data:tx}=await admin.from("payment_transactions").select("*").eq("id",id).eq("merchant_id",visible.merchant_id).maybeSingle();if(!tx)return NextResponse.json({error:"Not found"},{status:404});if(tx.status!=="requires_review")return NextResponse.json({error:"Transaction is not awaiting review"},{status:409});
 if(parsed.data.decision==="reject"){const {data,error}=await admin.from("payment_transactions").update({status:"cancelled",failure_code:"MANUAL_REVIEW_REJECTED",failure_message:"Rejected during manual review",updated_at:new Date().toISOString()}).eq("id",id).select("*").single();await admin.from("transaction_events").insert({transaction_id:id,type:"review_rejected",detail:`Rejected by ${auth.user.email||auth.user.id}`});return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json(data)}
 try{const provider=selectProvider(tx.currency);const callbackUrl=new URL(`/payments/${tx.reference}`,req.nextUrl.origin).toString();const checkout=await initializeCheckout(provider,{reference:tx.reference,amountMinor:BigInt(tx.amount_minor),currency:tx.currency,customerEmail:tx.customer_email,callbackUrl,metadata:{...(tx.metadata||{}),vortix_transaction_id:tx.id,merchant_id:tx.merchant_id,manual_review_approved:true}});const {data,error}=await admin.from("payment_transactions").update({status:"pending",provider:checkout.provider,provider_reference:checkout.providerReference,authorization_url:checkout.authorizationUrl,route_reason:`Manual review approved; ${checkout.provider} checkout initialized`,failure_code:null,failure_message:null,updated_at:new Date().toISOString()}).eq("id",id).select("*").single();if(error)throw error;await admin.from("transaction_events").insert({transaction_id:id,type:"review_approved",detail:`Approved by ${auth.user.email||auth.user.id}`});return NextResponse.json({...data,checkout:{authorizationUrl:checkout.authorizationUrl,provider:checkout.provider}})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to initialize checkout after approval"},{status:503})}
}
