import {useCallback,useEffect,useMemo,useState} from "react";
import {Alert,SafeAreaView,ScrollView,Text,TextInput,TouchableOpacity,View,useColorScheme,RefreshControl} from "react-native";
import * as SecureStore from "expo-secure-store";
import {StatusBar} from "expo-status-bar";

const SUPABASE_URL="https://yjzxrrwlgezwmzjxlouu.supabase.co";
const SUPABASE_KEY="sb_publishable_hoDCXgzOjyHrcMYadKBw_A_st8Zdaf5";
type Tx={id:string;reference:string;amount_minor:string;currency:string;status:string;risk_score:number;provider:string|null};
type Session={access_token:string;refresh_token:string};
type Me={membership:{role:string;merchant:{id:string;name:string}}|null;user:{email?:string}|null};

export default function App(){
 const dark=useColorScheme()!=="light";const c={bg:dark?"#07101d":"#f5f8fc",card:dark?"#0e1a2b":"#fff",text:dark?"#f5f8ff":"#122033",muted:dark?"#8fa3bf":"#637793",border:dark?"#203451":"#d8e2ef",accent:"#4f8cff"};
 const [baseUrl,setBaseUrl]=useState(""),[session,setSession]=useState<Session|null>(null),[me,setMe]=useState<Me|null>(null),[items,setItems]=useState<Tx[]>([]),[loading,setLoading]=useState(false),[mode,setMode]=useState<"login"|"signup">("login");
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[fullName,setFullName]=useState(""),[company,setCompany]=useState("");
 useEffect(()=>{(async()=>{setBaseUrl((await SecureStore.getItemAsync("vortixBaseUrl"))||"");const access=await SecureStore.getItemAsync("vortixAccessToken"),refresh=await SecureStore.getItemAsync("vortixRefreshToken");if(access&&refresh)setSession({access_token:access,refresh_token:refresh})})()},[]);
 async function storeSession(s:Session|null){setSession(s);if(s){await SecureStore.setItemAsync("vortixAccessToken",s.access_token);await SecureStore.setItemAsync("vortixRefreshToken",s.refresh_token)}else{await SecureStore.deleteItemAsync("vortixAccessToken");await SecureStore.deleteItemAsync("vortixRefreshToken")}}
 async function auth(path:string,body:Record<string,unknown>){const r=await fetch(`${SUPABASE_URL}${path}`,{method:"POST",headers:{"content-type":"application/json","apikey":SUPABASE_KEY},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.msg||d.error_description||d.message||"Authentication failed");return d}
 async function signIn(){try{const d=await auth("/auth/v1/token?grant_type=password",{email,password});await storeSession(d);setPassword("")}catch(e){Alert.alert("Sign in failed",e instanceof Error?e.message:"Unable to sign in")}}
 async function signUp(){try{const d=await auth("/auth/v1/signup",{email,password,data:{full_name:fullName,company_name:company}});if(d.access_token){await storeSession(d)}else{Alert.alert("Check your email","Your Vortix account was created. Confirm your email, then sign in.");setMode("login")}setPassword("")}catch(e){Alert.alert("Sign up failed",e instanceof Error?e.message:"Unable to create account")}}
 const apiHeaders=useMemo(()=>session?{Authorization:`Bearer ${session.access_token}`}:{},[session]);
 const load=useCallback(async()=>{if(!baseUrl||!session)return;setLoading(true);try{const [mr,tr]=await Promise.all([fetch(baseUrl.replace(/\/$/,"")+"/api/v1/me",{headers:apiHeaders}),fetch(baseUrl.replace(/\/$/,"")+"/api/v1/transactions",{headers:apiHeaders})]);if(mr.status===401||tr.status===401){await storeSession(null);setMe(null);setItems([]);return}if(mr.ok)setMe(await mr.json());if(tr.ok)setItems(await tr.json())}catch{Alert.alert("Connection error","Unable to reach your Vortix deployment.")}finally{setLoading(false)}},[baseUrl,session,apiHeaders]);
 useEffect(()=>{if(baseUrl&&session)void load()},[baseUrl,session,load]);
 async function saveUrl(){const clean=baseUrl.trim().replace(/\/$/,"");await SecureStore.setItemAsync("vortixBaseUrl",clean);setBaseUrl(clean);if(session)void load()}
 async function logout(){await storeSession(null);setMe(null);setItems([])}
 if(!session)return <SafeAreaView style={{flex:1,backgroundColor:c.bg}}><StatusBar style={dark?"light":"dark"}/><ScrollView contentContainerStyle={{padding:24,gap:14}}><Text style={{color:c.muted}}>Vortix mobile</Text><Text style={{color:c.text,fontSize:34,fontWeight:"800"}}>{mode==="login"?"Sign in":"Create merchant account"}</Text><TextInput placeholder="Vortix deployment URL" placeholderTextColor={c.muted} value={baseUrl} onChangeText={setBaseUrl} autoCapitalize="none" style={{color:c.text,borderColor:c.border,borderWidth:1,borderRadius:12,padding:13}}/>{mode==="signup"&&<><TextInput placeholder="Full name" placeholderTextColor={c.muted} value={fullName} onChangeText={setFullName} style={{color:c.text,borderColor:c.border,borderWidth:1,borderRadius:12,padding:13}}/><TextInput placeholder="Company name" placeholderTextColor={c.muted} value={company} onChangeText={setCompany} style={{color:c.text,borderColor:c.border,borderWidth:1,borderRadius:12,padding:13}}/></>}<TextInput placeholder="Email" placeholderTextColor={c.muted} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" style={{color:c.text,borderColor:c.border,borderWidth:1,borderRadius:12,padding:13}}/><TextInput placeholder="Password" placeholderTextColor={c.muted} value={password} onChangeText={setPassword} secureTextEntry style={{color:c.text,borderColor:c.border,borderWidth:1,borderRadius:12,padding:13}}/><TouchableOpacity onPress={async()=>{await saveUrl();mode==="login"?await signIn():await signUp()}} style={{backgroundColor:c.accent,borderRadius:12,padding:14}}><Text style={{color:"white",fontWeight:"800",textAlign:"center"}}>{mode==="login"?"Sign in":"Create account"}</Text></TouchableOpacity><TouchableOpacity onPress={()=>setMode(mode==="login"?"signup":"login")}><Text style={{color:c.accent,textAlign:"center"}}>{mode==="login"?"New to Vortix? Create an account":"Already have an account? Sign in"}</Text></TouchableOpacity></ScrollView></SafeAreaView>;
 const review=items.filter(x=>x.status==="requires_review").length,succeeded=items.filter(x=>x.status==="succeeded").length;
 return <SafeAreaView style={{flex:1,backgroundColor:c.bg}}><StatusBar style={dark?"light":"dark"}/><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={{padding:20,gap:16}}><View><Text style={{color:c.muted}}>{me?.membership?.merchant?.name||"Vortix merchant"}</Text><Text style={{color:c.text,fontSize:32,fontWeight:"800",marginTop:5}}>Payment control plane</Text></View><View style={{flexDirection:"row",gap:10}}>{[["Transactions",items.length],["Review",review],["Succeeded",succeeded]].map(([a,b])=><View key={String(a)} style={{flex:1,backgroundColor:c.card,borderColor:c.border,borderWidth:1,borderRadius:16,padding:14}}><Text style={{color:c.muted,fontSize:12}}>{a}</Text><Text style={{color:c.text,fontSize:22,fontWeight:"800",marginTop:6}}>{b}</Text></View>)}</View><View style={{gap:10}}><Text style={{color:c.text,fontSize:18,fontWeight:"700"}}>Recent transactions</Text>{items.map(x=><View key={x.id} style={{backgroundColor:c.card,borderColor:c.border,borderWidth:1,borderRadius:16,padding:16}}><View style={{flexDirection:"row",justifyContent:"space-between",gap:10}}><Text style={{color:c.text,fontWeight:"700",flex:1}}>{x.reference}</Text><Text style={{color:x.status==="requires_review"?"#ffb84d":x.status==="succeeded"?"#31d0aa":c.muted,fontWeight:"700"}}>{x.status}</Text></View><Text style={{color:c.muted,marginTop:7}}>{x.currency} {(Number(x.amount_minor)/100).toLocaleString()} · risk {x.risk_score} · {x.provider||"unrouted"}</Text></View>)}{items.length===0&&<Text style={{color:c.muted}}>No transactions yet.</Text>}</View><View style={{backgroundColor:c.card,borderColor:c.border,borderWidth:1,borderRadius:16,padding:16,gap:10}}><Text style={{color:c.text,fontWeight:"700"}}>Connection</Text><TextInput value={baseUrl} onChangeText={setBaseUrl} autoCapitalize="none" style={{color:c.text,borderColor:c.border,borderWidth:1,borderRadius:10,padding:12}}/><TouchableOpacity onPress={saveUrl} style={{backgroundColor:c.accent,borderRadius:10,padding:12}}><Text style={{color:"white",fontWeight:"800",textAlign:"center"}}>Save URL</Text></TouchableOpacity><TouchableOpacity onPress={logout}><Text style={{color:"#ff6978",textAlign:"center"}}>Sign out</Text></TouchableOpacity></View></ScrollView></SafeAreaView>
}
